### ISSUE TITLE
Move gestures to "Gestures"-menu

### ISSUE THREAD

**Issue by Liggliluff** [sandymanu/hammerhead_nkernel#5]
"Double-tap to sleep" and "Volume rocker wake" are both placed under "Display"; however, Google has moved such actions to the menu "Gestures" instead.

These two otions should simply be moved to the "Gestures"-menu.

**Comment by sandymanu** [comment]
This is a kernel source :)

**Comment by Liggliluff** [comment]
Sorry for disturbing then. But where should I go to find this then?
