### ISSUE TITLE
Missing translations for new menu options

### ISSUE THREAD

**Issue by Liggliluff** [sandymanu/hammerhead_nkernel#6]
The following new strings are missing translations:
Sytem settings > Display > Double-tap to sleep
Sytem settings > Display > Volume rocker wake
Power menu > Screenshot
Power menu > Restart > Restart
Power menu > Restart > Soft Restart

And these should also be allowed to be translated just in case:
Power menu > Restart > Recovery
Power menu > Restart > Bootloader

Is there a way for us to provide crowd sourced translations for these?

**Comment by sandymanu** [comment]
This is a kernel source :)

As for the other question, there is no way to provide crowd sourced translation

**Comment by Liggliluff** [comment]
Could you elaborate for me, and pell me where I should go?
