### ISSUE TITLE
fs/namei.c:2802:2: warning: 'name' may be used uninitialized in this function [-Wmaybe-uninitialized]

### ISSUE THREAD

**Issue by ReeSilva** [sandymanu/hammerhead_nkernel#9]
Hey @sandymanu ,

when I'm trying to compile the kernel in the Oreo branch, I'm getting the follow error:
```
fs/namei.c: In function 'do_rmdir':
fs/namei.c:2802:2: warning: 'name' may be used uninitialized in this function [-Wmaybe-uninitialized]
error, forbidden warning: namei.c:2802
make[1]: *** [scripts/Makefile.build:307: fs/namei.o] Error 1
make: *** [Makefile:950: fs] Error 2
```

Any tip on how to solve it?

System: Manjaro Linux with kernel 4.9.43
Perl 5.26
Python 2.7
OpenJDK 8

Best regards.

**Comment by sandymanu** [comment]
You are trying to compile a bit earlier i guess. I am not finished pushing entirely :)

**Comment by ReeSilva** [comment]
Oh, I thought so LOL But I had to check first If there was anything that I could been doing wrong. Since there is not, I'll try to fix by myself.

Cheers.
